apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sre-challenge.fullname" . }}-config
  labels:
    {{- include "sre-challenge.labels" . | nindent 4 }}
data:
  # Learning Opportunity: 
  # Decoupling configuration (URLs, Flags) from the Deployment code.
  # If we change the Backend URL, we verify the ConfigMap, not the Pod spec.
  BACKEND_URL: {{ .Values.frontend.config.backendUrl | quote }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  REDIS_HOST: "{{ include "sre-challenge.fullname" . }}-redis" # Service Discovery name
